imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

services:
    my.facebook.user:
        class: Likeme\SystemBundle\Security\User\Provider\FacebookProvider
        arguments:
            facebook: "@fos_facebook.api"
            userManager: "@fos_user.user_manager"
            validator: "@validator"
            container: "@service_container"     
    likeme.gaufrette.stream_registry:
        class: Likeme\SystemBundle\Gaufrette\StreamRegistry
    #
    # Amazon adapters
    #
    likeme.amazon_s3:
        class: Likeme\SystemBundle\Gaufrette\AmazoneWithoutSSL
        arguments: 
            -
                key:  %amazon_s3.key%
                secret: %amazon_s3.secret%
        calls:
            - [setSSL]
    likeme.amazon_s3.base_adapter:
        class: Gaufrette\Adapter\AmazonS3
        arguments: 
            service: @likeme.amazon_s3
            bucket_name: %amazon_s3.bucket%
    likeme.amazon_s3.adapter:
        class: Gaufrette\Adapter\AclAwareAmazonS3
        arguments:
            - "@likeme.amazon_s3.base_adapter"
            - "@likeme.amazon_s3"
            - %amazon_s3.bucket%
        calls:
            - [ setAclConstant, [ 'public' ] ]
    #
    # Filesystem adapters
    #
    likeme.local_filesystem.adapter:
        class: Gaufrette\Adapter\Local
        arguments:
            - %kernel.root_dir%/../web/media/cache/
            - true
    #
    # Filesystems
    #
    gaufrette.filesystem.media_cache:
        class: Gaufrette\Filesystem
        arguments:
            - "@likeme.amazon_s3.adapter"
        tags:
            - { name: 'likeme.stream_filesystem', alias: 'media_cache' }

    gaufrette.filesystem.local_filesystem_cache:
        class: Gaufrette\Filesystem
        arguments:
            - "@likeme.local_filesystem.adapter"
        tags:
            - { name: 'likeme.stream_filesystem', alias: 'local_filesystem_cache' } 
    #
    # Imagine
    #
    likeme.imagine.data.loader.media_cache:
        class: "%liip_imagine.data.loader.stream.class%"
        arguments:
            - "@liip_imagine"
            - 'gaufrette://media_cache/'
        tags:
            - { name: 'liip_imagine.data.loader', loader: 'media_cache' }

    likeme.imagine.cache.resolver.amazon_s3:
        class: Liip\ImagineBundle\Imagine\Cache\Resolver\AmazonS3Resolver
        arguments:
            - "@likeme.amazon_s3"
            - "%amazon_s3.bucket%"
        calls:
            - [ setLogger, [ @logger ] ]
        tags:
            - { name: 'liip_imagine.cache.resolver', resolver: 'amazon_s3' }
          
framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false 
    
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Likeme\SystemBundle\Entity\User
    profile:
        form:
            handler: likeme_user.form.handler.profile

fos_facebook:
      file:   %kernel.root_dir%/../vendor/facebook/src/base_facebook.php
      alias:  facebook
      app_id: 100806270069332
      secret: 98c29a3bd105813b3308e24a404d23f1
      cookie: true
      permissions: [email, user_birthday, user_location, user_photos, user_about_me, user_location]
      
liip_imagine:
    driver:               gd
    web_root:             %kernel.root_dir%/../web
    data_root:            %kernel.root_dir%/../web
    controller_action:    liip_imagine.controller:filterAction
    formats:              []
    filter_sets:
        my_thumb:
            quality: 75
            filters:
                thumbnail: { size: [120, 90], mode: outbound }
        thumbnails:
            cache: 'amazon_s3'
            data_loader: media_cache
            quality: 75
            filters:
                thumbnail: { size: [400, 400], mode: outbound }

apy_js_form_validation:
    enabled: true
    yui_js: false
    check_mode: both
    javascript_framework: jquery
    validation_bundle: APYJsFormValidationBundle
    script_directory: bundles/jsformvalidation/js/
    warmer_routes: [route1,route2]
    
    