likemeToplikedBundle:
    resource: "@likemeToplikedBundle/Resources/config/routing.yml"
    prefix:   /

likemeRandomBundle:
    resource: "@likemeRandomBundle/Resources/config/routing.yml"
    prefix:   /

likemeLikingBundle:
    resource: "@likemeLikingBundle/Resources/config/routing.yml"
    prefix:   /

likemeMessageBundle:
    resource: "@likemeMessageBundle/Resources/config/routing.yml"
    prefix:   /

likemeProfileBundle:
    resource: "@likemeProfileBundle/Resources/config/routing.yml"
    prefix:   /

likemeSpamBundle:
    resource: "@likemeSpamBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
