_welcome:
    pattern:  /
    defaults: { _controller: AcmeDemoBundle:Welcome:index }

_demo_secured:
    resource: "@AcmeDemoBundle/Controller/SecuredController.php"
    type:     annotation

_demo:
    resource: "@AcmeDemoBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo

_assetic:
    resource: .
    type:     assetic

_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml



likemeToplikedBundle:
    resource: "@likemeToplikedBundle/Resources/config/routing.yml"
    prefix:   /

likemeRandomBundle:
    resource: "@likemeRandomBundle/Resources/config/routing.yml"
    prefix:   /

likemeLikingBundle:
    resource: "@likemeLikingBundle/Resources/config/routing.yml"
    prefix:   /

likemeMessageBundle:
    resource: "@likemeMessageBundle/Resources/config/routing.yml"
    prefix:   /

likemeProfileBundle:
    resource: "@likemeProfileBundle/Resources/config/routing.yml"
    prefix:   /

likemeSpamBundle:
    resource: "@likemeSpamBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
