security:
    factories:
        - "%kernel.root_dir%/../vendor/bundles/FOS/FacebookBundle/Resources/config/security_factories.xml"
    providers:
        # choose the provider name freely
        fos_userbundle:
            id: fos_user.user_manager
        my_fos_facebook_provider:
            id: my.facebook.user

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: /afterlogin
                login_path: /
            fos_facebook:
                app_url:    "http://www.facebook.com/apps/application.php?id=100806270069332"
                server_url: "http://www.likeme.ch/"
                login_path: user_home #/
                check_path: _security_check #/login_fb_check
                default_target_path: /afterlogin
                provider: my_fos_facebook_provider
                #provider: fos_userbundle
            logout:
                handlers: ["likeme_facebook.logout_handler"]
                #delete_cookies:
                #    fbs_100806270069332: { path: "/", domain: "likeme.ch" }
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN