services:
    likeme.menu_builder:
        class: Likeme\SystemBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", '@security.context']

    likeme.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: likeme.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu
            
    likeme_user.form.handler.profile:
        class: Likeme\SystemBundle\Form\Handler\ProfileFormHandler
        arguments: ["@fos_user.registration.form", "@request", "@fos_user.user_manager", "@fos_user.mailer"]
        scope: request
        public: false
        
    likeme.twig.extension:
        class: Likeme\SystemBundle\Extension\TextExtension
        tags:
            - { name: twig.extension }
        
    likeme.facebook.updatetoken:
        class: Likeme\SystemBundle\Extension\FacebookToken
        
    likeme.facebook.location:
        class: Likeme\SystemBundle\Extension\FacebookLocation
        calls:
            - [ setContainer, [ @service_container ] ]
            
    likeme_facebook.logout_handler:
        #class: FOS\FacebookBundle\Security\Logout\FacebookHandler
        class: Likeme\SystemBundle\Security\Logout\FacebookHandler
        public: false
        arguments: ["@fos_facebook.api", "@service_container"]
        