<?php

namespace likeme\MessageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * messagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class messagesRepository extends EntityRepository
{
}