<?php

namespace likeme\SpamBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SpamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpamRepository extends EntityRepository
{
}