<?php

namespace Likeme\SystemBundle\Entity;

use Likeme\SystemBundle\Controller\LocationController;

use Doctrine\ORM\EntityRepository;

/**
 * PicturesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
}