<?php

namespace Likeme\SystemBundle\Entity;

use Likeme\SystemBundle\Controller\LocationController;

use Doctrine\ORM\EntityRepository;

/**
 * PicturesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	/*
	private $locationByFacebook;
	
	public function __construct()
	{
		parent::__construct();
	
		$this->locationByFacebook = new LocationController();
	}*/
	
	public function facebookInit($location) 
	{
		//return $this->locationByFacebook->locationByFacebookAction($location);
	}
}