<?php

namespace likeme\ToplikedBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ToplikedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ToplikedRepository extends EntityRepository
{
}