likeme\ProfileBundle\Entity\Pictures:
  type: entity
  table: pictures
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
    profileId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: profile_id
    src:
      type: string
      length: 255
      fixed: false
      nullable: true
    isProfile:
      type: integer
      unsigned: false
      nullable: true
      column: is_profile
    timestamp:
      type: datetime
      nullable: false
  lifecycleCallbacks: {  }
