likeme\ProfileBundle\Entity\Plzdb:
  type: entity
  table: plzdb
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      column: ID
      generator:
        strategy: IDENTITY
    country:
      type: string
      length: 2
      fixed: false
      nullable: false
      column: Country
    language:
      type: string
      length: 2
      fixed: false
      nullable: false
      column: Language
    iso2:
      type: string
      length: 6
      fixed: false
      nullable: false
      column: ISO2
    region1:
      type: string
      length: 60
      fixed: false
      nullable: false
      column: Region1
    region2:
      type: string
      length: 60
      fixed: false
      nullable: false
      column: Region2
    region3:
      type: string
      length: 60
      fixed: false
      nullable: false
      column: Region3
    region4:
      type: string
      length: 60
      fixed: false
      nullable: false
      column: Region4
    zip:
      type: string
      length: 10
      fixed: false
      nullable: false
      column: ZIP
    city:
      type: string
      length: 60
      fixed: false
      nullable: false
      column: City
    area1:
      type: string
      length: 80
      fixed: false
      nullable: false
      column: Area1
    area2:
      type: string
      length: 80
      fixed: false
      nullable: false
      column: Area2
    lat:
      type: float
      nullable: false
      column: Lat
    lng:
      type: float
      nullable: false
      column: Lng
    tz:
      type: string
      length: 30
      fixed: false
      nullable: false
      column: TZ
    utc:
      type: string
      length: 10
      fixed: false
      nullable: false
      column: UTC
    dst:
      type: string
      length: 1
      fixed: false
      nullable: false
      column: DST
  lifecycleCallbacks: {  }
