likemeSpamBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: likemeSpamBundle:Default:index }

_newSpam:
    pattern: /newSpam/
    defaults: { _controller: likemeSpamBundle:Default:newSpam }

_listSpam:
    pattern: /listSpam/
    defaults: { _controller: likemeSpamBundle:Default:listSpam }
    
_delSpam:
    pattern: /delSpam/{id}
    defaults: { _controller: likemeSpamBundle:Default:delSpam }
    
_modSpam:
    pattern: /modSpam/{id}
    defaults: { _controller: likemeSpamBundle:Default:modSpam }