likemeSpamBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: likemeSpamBundle:Default:index }

_newSpam:
    pattern: /newSpam/
    defaults: { _controller: likemeSpamBundle:Default:newSpam }

_listSpam:
    pattern: /listSpam/
    defaults: { _controller: likemeSpamBundle:Default:listSpam }