parameters:
#    likeme_spam.example.class: likeme\SpamBundle\Example

services:
#    likeme_spam.example:
#        class: %likeme_spam.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
