parameters:
#    likeme_random.example.class: likeme\RandomBundle\Example

services:
#    likeme_random.example:
#        class: %likeme_random.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
